version: "3.7"

services:
  clientes:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/clientes
      spring.jpa.generate-ddl: true
      spring.jpa.hibernate.ddl-auto: update
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clientes

volumes:
  mysqldb:
