server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientes
    username: root
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq